#ifndef INCLUDE_INCLUDE_CHESS_H_
#define INCLUDE_INCLUDE_CHESS_H_

enum ChessPieces {
  CHESS_NONE = 0,
  CHESS_PAWN_BLACK,
  CHESS_PAWN_WHITE,
  CHESS_ROOK_BLACK,
  CHESS_ROOK_WHITE,
  CHESS_HORSE_BLACK,
  CHESS_HORSE_WHITE,
  CHESS_BISHOP_BLACK,
  CHESS_BISHOP_WHITE,
  CHESS_QUEEN_BLACK,
  CHESS_QUEEN_WHITE,
  CHESS_KING_BLACK,
  CHESS_KING_WHITE
};

#endif // INCLUDE_INCLUDE_CHESS_H_
